name: Release flow

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

env:
  S3_BUCKET: ntp-help.ru
  DIST_PATH: dist/

jobs:
  setup:
    name: Checkout & generate changelog
    runs-on: ubuntu-latest

    outputs:
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-message: 'chore(release): {version}'
          release-count: 0

  build:
    name: Build distributive
    needs: [ setup ]
    if: ${{ needs.setup.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm run generate

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ env.DIST_PATH }}
          retention-days: 3

  deploy:
    name: Deploy distributive
    needs: [ setup, build ]
    if: ${{ needs.setup.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download distributive artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Upload to bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_REGION: ru-central1
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
